### ISSUE TITLE
您好，项目跑起来之后，首页报错

### ISSUE THREAD

**Issue by yhtt2020** [SHEE94/unibrowser#1]
首页报
项目database目录下缺少news_line.schema.json。如云端的该表已配置schema，请下载到database目录中。
精选应用那边也报类似的错误。
看了代码好像没有对应的json。
请问这个要怎么办呢？

**Comment by SHEE94** [comment]
因为首页之前使用了云开发代码拉取数据，可以忽略云开发的报错，现在已经修复了
